# Copyright (C) 2017-2018 52°North Initiative for
# Geospatial Open Source Software GmbH
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as published
# by the Free Software Foundation.
#
# If the program is linked with libraries which are licensed under one of
# the following licenses, the combination of the program with the linked
# library is not considered a "derivative work" of the program:
#
#     - Apache License, version 2.0
#     - Apache Software License, version 1.0
#     - GNU Lesser General Public License, version 3
#     - Mozilla Public License, versions 1.0, 1.1 and 2.0
#     - Common Development and Distribution License (CDDL), version 1.0
#
# Therefore the distribution of the program linked with libraries licensed
# under the aforementioned licenses, is permitted by the copyright holders
# if the distribution is compliant with both the GNU General Public
# License version 2 and the aforementioned licenses.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
# Public License for more details.
#
#
#  run via
#
#    docker-compose up --force-recreate --remove-orphans
#
#  from repository root folder
version: '2'
services:
  db:
    image: mdillon/postgis:9.5-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sos
    volumes:
      - "./db/init-dakamon-db-schema.sql:/docker-entrypoint-initdb.d/zz_init.sql"
      - "./db/clean-database.sql:/clean-database.sql"
      #- "dakamon-sos-db:/var/lib/postgresql/data"
    networks:
      network:
        ipv4_address: 172.23.52.101
  sos:
    image: sos:dakamon-2018-08
    ports:
      - 8080:8080
      - 8000:8000
    links:
      - db:postgres
    depends_on:
      - db
    environment:
      - JPDA_ADDRESS=8000
      - JPDA_TRANSPORT=dt_socket
    volumes:
      - "./sos/configuration.db:/usr/local/tomcat/webapps/52n-sos-webapp/configuration.db"
      - "./sos/settings.json:/usr/local/tomcat/webapps/52n-sos-webapp/static/client/helgoland/settings.json"
      - "./sos/datasource.properties:/usr/local/tomcat/webapps/52n-sos-webapp/WEB-INF/datasource.properties"
      - "./sos/application.properties:/usr/local/tomcat/webapps/52n-sos-webapp/WEB-INF/classes/application.properties"
    command: ["catalina.sh", "jpda", "run"]
    networks:
      network:
        ipv4_address: 172.23.52.102
  shiny:
    image: shiny-server:dakamon-2018-08
    ports:
      - 3838:3838
    depends_on:
      - db
    links:
      - db:postgres
    networks:
      network:
        ipv4_address: 172.23.52.103
  proxy:
    image: nginx:mainline-alpine
    ports:
      - 80:80
    depends_on:
      - shiny
      - sos
    links:
      - sos:sos
    volumes:
      - "./proxy/proxy.conf:/etc/nginx/conf.d/default.conf"
      - "./proxy/index.html:/usr/share/nginx/html/index.html"
      - "./proxy/img:/usr/share/nginx/html/img"
      - "./proxy/js:/usr/share/nginx/html/js"
      - "./proxy/css:/usr/share/nginx/html/css"
      - "./proxy/fonts:/usr/share/nginx/html/fonts"
    networks:
      network:
        ipv4_address: 172.23.52.104
networks:
  network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.23.52.0/24
